# developブランチへのPRにdevelopタグを設定する

name: Labeler Main
on:
  pull_request:
    branches:
      - main

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler-main.yml"
